services:
  teledrop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_DOMAIN=localhost
    container_name: teledrop
    ports:
      - 80:8000/tcp
    volumes:
      - ./share:/teledrop/share
    environment:
      - TZ=Asia/Seoul
