services:
  teledrop:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOST_DOMAIN=localhost # edit here to your domain or ip to serve
    container_name: teledrop
    restart: unless-stopped
    ports:
      - 80:8000/tcp
    volumes:
      - ./share:/teledrop/share
    environment:
      - TZ=Asia/Seoul
      - WEB_USERNAME=
      - WEB_PASSWORD=
