services:
  teledrop:
    image: ghcr.io/onejajae/teledrop:main
    container_name: teledrop
    restart: unless-stopped
    ports:
      - 80:8000/tcp
    volumes:
      - ./share:/teledrop/share
    environment:
      - TZ=Asia/Seoul
      - WEB_USERNAME=
      - WEB_PASSWORD=
